import { spawn } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import * as core from '@actions/core';
import * as github from '@actions/github';

export interface ActionInputs {
  configPath: string;
  severityThreshold: string;
  failOnFindings: boolean;
  commentPr: boolean;
  baselinePath: string;
  offline: boolean;
  mcpvetCommand: string;
  githubToken: string;
}

export interface ActionOutputs {
  findingsCount: number;
  riskScore: number;
  hasCritical: boolean;
  resultPath: string;
  exitCode: number;
}

/** Read inputs from the GitHub Actions environment. */
export function readInputs(): ActionInputs {
  return {
    configPath: core.getInput('config-path') || '.',
    severityThreshold: core.getInput('severity-threshold') || 'low',
    failOnFindings: (core.getInput('fail-on-findings') || 'true').toLowerCase() !== 'false',
    commentPr: (core.getInput('comment-pr') || 'true').toLowerCase() !== 'false',
    baselinePath: core.getInput('baseline-path') || '.mcpvet/baseline.json',
    offline: (core.getInput('offline') || 'false').toLowerCase() === 'true',
    mcpvetCommand: core.getInput('mcpvet-command') || 'npx mcpvet',
    githubToken: core.getInput('github-token') || process.env.GITHUB_TOKEN || '',
  };
}

/** Build the `mcpvet scan` command line. Split for spawn(). */
export function buildArgs(inputs: ActionInputs): { cmd: string; baseArgs: string[] } {
  const [cmd, ...baseArgs] = inputs.mcpvetCommand.split(/\s+/);
  const args = [
    ...baseArgs,
    'scan',
    '--json',
    '--severity',
    inputs.severityThreshold,
    '--cwd',
    inputs.configPath,
  ];
  if (inputs.offline) args.push('--offline');
  if (inputs.baselinePath) args.push('--baseline', inputs.baselinePath);
  return { cmd: cmd ?? 'npx', baseArgs: args };
}

/** Spawn the mcpvet scan and capture its output. Resolves with code+stdout+stderr. */
export function runScan(
  cmd: string,
  args: string[],
  env: NodeJS.ProcessEnv = process.env,
): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolveP, rejectP) => {
    const child = spawn(cmd, args, { env, stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout?.on('data', (chunk: Buffer) => {
      stdout += chunk.toString();
    });
    child.stderr?.on('data', (chunk: Buffer) => {
      stderr += chunk.toString();
    });
    child.on('error', rejectP);
    child.on('close', (code) => resolveP({ code: code ?? -1, stdout, stderr }));
  });
}

/** Format the scan result as a markdown PR comment body. */
export function formatCommentBody(json: ScanJson): string {
  const findings = json.scan.findings;
  const score = json.scan.score;

  const emoji = score.level === 'critical' || score.level === 'high' ? '🚨' : '✅';
  const lines: string[] = [];
  lines.push(`## ${emoji} mcpvet — risk ${score.value}/100 (${score.level})`);
  lines.push('');
  lines.push(
    `Scanned **${json.scan.servers.length}** MCP server(s) and found **${findings.length}** finding(s).`,
  );
  lines.push('');

  if (findings.length === 0) {
    lines.push('No issues found. ✅');
  } else {
    lines.push('### Findings');
    lines.push('');
    lines.push('| Severity | Server | Pattern | Match |');
    lines.push('| --- | --- | --- | --- |');
    for (const f of findings) {
      const where = f.toolName ? `\`${f.serverName}\` (\`${f.toolName}\`)` : `\`${f.serverName}\``;
      const snippet = f.snippet.replace(/\|/g, '\\|').slice(0, 100);
      lines.push(`| ${sev(f.severity)} | ${where} | \`${f.patternId}\` | ${snippet} |`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push(
    `<sub>Generated by [mcpvet](https://github.com/mcpvetio/mcpvet) v${json.scan.toolVersion}</sub>`,
  );
  return lines.join('\n');
}

function sev(s: string): string {
  return (
    {
      critical: '🔴 critical',
      high: '🟠 high',
      medium: '🟡 medium',
      low: '🔵 low',
      info: '⚪ info',
    }[s] ?? s
  );
}

export interface ScanJson {
  scan: {
    findings: Array<{
      id: string;
      patternId: string;
      severity: string;
      serverName: string;
      toolName?: string;
      field: string;
      snippet: string;
      references: string[];
    }>;
    score: { value: number; level: string };
    servers: unknown[];
    toolVersion: string;
  };
}

/** Post or update a PR comment with the scan results. Idempotent — looks for an
 *  existing mcpvet comment and updates it instead of duplicating. */
export async function postOrUpdateComment(
  token: string,
  body: string,
  marker = '<!-- mcpvet-scan -->',
): Promise<{ action: 'created' | 'updated' | 'skipped'; htmlUrl?: string }> {
  if (!token) {
    core.warning('No GitHub token; skipping PR comment');
    return { action: 'skipped' };
  }
  const context = github.context;
  if (!context.payload.pull_request) {
    core.info('Not a pull_request event; skipping comment');
    return { action: 'skipped' };
  }
  const octokit = github.getOctokit(token);
  const { owner, repo } = context.repo;
  const issueNumber = context.payload.pull_request.number;

  // Find existing mcpvet comment
  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: issueNumber,
    per_page: 100,
  });
  const existing = comments.find((c) => c.body?.includes(marker));

  const fullBody = `${marker}\n${body}`;

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body: fullBody,
    });
    return { action: 'updated' };
  }

  const { data: created } = await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body: fullBody,
  });
  return { action: 'created', htmlUrl: created.html_url };
}

/** Set the GitHub Action outputs. In tests, this is a no-op. */
export function setOutputs(outputs: ActionOutputs): void {
  core.setOutput('findings-count', String(outputs.findingsCount));
  core.setOutput('risk-score', String(outputs.riskScore));
  core.setOutput('has-critical', outputs.hasCritical ? 'true' : 'false');
  core.setOutput('result-path', outputs.resultPath);
  core.setOutput('exit-code', String(outputs.exitCode));
}

/** Main action entrypoint. Exported separately for testing. */
export async function run(): Promise<void> {
  try {
    const inputs = readInputs();
    const { cmd, baseArgs } = buildArgs(inputs);
    core.debug(`running: ${cmd} ${baseArgs.join(' ')}`);

    const result = await runScan(cmd, baseArgs);
    if (result.stderr) core.info(result.stderr);

    let json: ScanJson;
    try {
      json = JSON.parse(result.stdout) as ScanJson;
    } catch (err) {
      core.setFailed(
        `mcpvet produced unparseable output (exit ${result.code}): ${(err as Error).message}`,
      );
      return;
    }

    // Write the result file as an artifact
    const resultPath = resolve(process.cwd(), 'mcpvet-result.json');
    await writeFile(resultPath, JSON.stringify(json, null, 2));
    core.debug(`wrote ${resultPath}`);

    const findingsCount = json.scan.findings.length;
    const riskScore = json.scan.score.value;
    const hasCritical = json.scan.score.level === 'critical';

    setOutputs({ findingsCount, riskScore, hasCritical, resultPath, exitCode: result.code });

    if (inputs.commentPr) {
      const body = formatCommentBody(json);
      const posted = await postOrUpdateComment(inputs.githubToken, body);
      core.info(`PR comment: ${posted.action}${posted.htmlUrl ? ` (${posted.htmlUrl})` : ''}`);
    }

    if (result.code !== 0 && inputs.failOnFindings) {
      core.setFailed(
        `mcpvet found ${findingsCount} issue(s) at ${inputs.severityThreshold}+ severity`,
      );
    }
  } catch (err) {
    core.setFailed((err as Error).message);
  }
}

// Re-export for tests that want to inspect the result file
export { readFile };

// Auto-run only when invoked as the action entrypoint, not when imported
if (process.env.MCPVET_ACTION_ENTRY === '1' || import.meta.url === `file://${process.argv[1]}`) {
  await run();
}
