import type { DiffResult, OriginInfo, ScanResult, Severity } from '../../types/index.js';

const SEVERITY_RANK = { info: 0, low: 1, medium: 2, high: 3, critical: 4 } as const;

export function formatMarkdown(scan: ScanResult, origins: OriginInfo[], diff?: DiffResult): string {
  const lines: string[] = [];
  const findings = scan.findings.filter((f) => SEVERITY_RANK[f.severity] >= SEVERITY_RANK.low);

  // Summary header — first line is the PR comment title
  const emoji = scan.score.level === 'critical' || scan.score.level === 'high' ? '🚨' : '✅';
  lines.push(`## ${emoji} mcpvet — risk ${scan.score.value}/100 (${scan.score.level})`);
  lines.push('');
  lines.push(
    `Scanned **${scan.servers.length}** MCP server(s) and found **${findings.length}** finding(s) at low+ severity.`,
  );
  lines.push('');

  if (findings.length === 0) {
    lines.push('No issues found. ✅');
  } else {
    lines.push('### Findings');
    lines.push('');
    lines.push('| Severity | Server | Pattern | Field | Match |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const f of findings) {
      const where = f.toolName ? `\`${f.serverName}\` (\`${f.toolName}\`)` : `\`${f.serverName}\``;
      const snippet = f.snippet.replace(/\|/g, '\\|').slice(0, 80);
      lines.push(
        `| ${sev(f.severity)} | ${where} | \`${f.patternId}\` | \`${f.field}\` | ${snippet} |`,
      );
    }
  }

  if (origins.length > 0) {
    lines.push('');
    lines.push('### Origin verification');
    lines.push('');
    lines.push('| Source | Name | Trust | Status |');
    lines.push('| --- | --- | --- | --- |');
    for (const o of origins) {
      const status = o.error
        ? '❌ error'
        : o.allowlisted
          ? '✅ allowlisted'
          : o.trustScore >= 70
            ? '✅ known'
            : '⚠️ unknown';
      const name = o.name ? `\`${o.name}\`` : '—';
      const trust = o.error ? '—' : String(o.trustScore);
      lines.push(`| ${o.source} | ${name} | ${trust} | ${status} |`);
    }
  }

  if (diff && diff.entries.length > 0) {
    lines.push('');
    lines.push('### Changes since baseline');
    lines.push('');
    for (const e of diff.entries) {
      const mark = e.kind === 'added' ? '➕' : e.kind === 'removed' ? '➖' : '✏️';
      lines.push(`- ${mark} ${e.summary}`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push(`*Generated by mcpvet v${scan.toolVersion}*`);
  return lines.join('\n');
}

function sev(s: Severity): string {
  return {
    critical: '🔴 critical',
    high: '🟠 high',
    medium: '🟡 medium',
    low: '🔵 low',
    info: '⚪ info',
  }[s];
}
